import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "space link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
